a = int(input()) 
b = int(input())
result = a + b
print(a, "+", b, "=", result)
result = a - b
print(a, "-" , b, "=", result)
result = a * b
print(a, "*", b, "=", result)
result = a / b
print(a, "/", b, "=", result)
