a = input() 
b = input()
result = a + b
print(a, "+", b, "=", result)
result = a - b
print(a, "-" , b, "=", result)
result = a * b
print(a, "*", b, "=", result)
result = a / b
print(a, "/", b, "=", result)
